export const ISSUES_FETCHING = "ISSUES_FETCHING";
export const ISSUES_SUCCESS = "ISSUES_SUCCESS";
export const ISSUES_ERROR = "ISSUES_ERROR";

export const ISSUE_FETCHING = "ISSUE_FETCHING";
export const ISSUE_SUCCESS = "ISSUE_SUCCESS";
export const ISSUE_ERROR = "ISSUE_ERROR";

export const ISSUE_COMMENTS_FETCHING = "ISSUE_COMMENTS_FETCHING";
export const ISSUE_COMMENTS_SUCCESS = "ISSUE_COMMENTS_SUCCESS";
export const ISSUE_COMMENTS_ERROR = "ISSUE_COMMENTS_ERROR";
